### PR TITLE
Improve data throughput for POST and PUT by reducing chunk length when using UART

### PR DESCRIPTION
**Pull request by Tagussan**
This pull request aims to improve the performance of POST and PUT data uploads by reducing the chunk length. By decreasing the chunk size from 1024 to 100, we observed the following speed-up:

- CHUNK_LENGTH = 1024: 1.2 MBit/s
- CHUNK_LENGTH = 100: **1.5** MBit/s

We conducted the measurement using a UART baudrate of 3M.

### CODE REVIEW

**Comment by RobMeades** [comment]
Hi, and thanks very much for this PR and the experimentation that backs it up.

It is kind of counter-intuitive that writing to file in smaller chunks is faster: did you happen to notice if the time for a GET (where the same chunk length is applied) was either (a) unaffected or (b) improved?  If it happened to be made worse for some reason we could introduce a different #define for the GET-side of things.

**Comment by RobMeades** [comment]
I've just talked to those on the module-side, a few more points/questions:

1.  At least in our SARA-R5 modules the flash-write length is fixed at 512 bytes, so underneath all of this, in the module, that is the kind of chunk size it will be operating in: did you happen to notice if the difference in speed came at somewhere just under 512 bytes, or was it specifically at 100 bytes?
2. The only reason they could think of as to why a shorter chunk size might be beneficial is if, on the module side, the task priority of whatever was writing to flash is blocking some other module-side task that is, somehow, involved in the PUT/POST process: in your experiment, are you doing single PUT/POSTs or are they in a series (in which case the writing to file for one in a large chunk might, possibly, block the actual PUTting/POSTing of data for the previous request)?

**Comment by Tagussan** [comment]
Hi! Thank you so much for your very quick response!

We are currently setting up an experimental environment to provide more detailed answers. We will share more detailed measurement data later!

We will answer your questions with the information we currently have before additional experiments are completed.

1. Impact on GET requests (download)
We are doing large uploads via PUT requests for our own projects, and we do not have a test program or environment for GET requests, so we cannot answer your questions immediately.

2. The number of bytes that began to cause changes in transfer rates (and why we decided to change the `CHUNK_LENGTH`)
We are using the NINA-W132. When we first used this device outdoors we noticed that the communication was very unstable. So we did a packet capture and found that we were getting a lot of TCP retransmissions from the device. We then lowered the `CHUNK_LENGTH` to 200 or 100 and found that the frequency of retransmissions dropped significantly and communication became more stable. Therefore, we do not know from which byte number there was a significant change in speed.

3. Task priority and other tasks:
We have created only one TCP connection, moved to data mode, and only a single file upload is being performed on the device.

**Comment by RobMeades** [comment]
Thanks for the update: just to confirm, in this scenario you are using a NINA-W132 as your communications device, i.e. using the [uHttpClient API](https://github.com/u-blox/ubxlib/blob/master/common/http_client/api/u_http_client.h) with `U_WIFI_MODULE_TYPE_NINA_W13`  or `U_SHORT_RANGE_MODULE_TYPE_NINA_W13` as your device?  If that is the case, what seems odd is that the parameter [U_HTTP_CLIENT_CELL_FILE_CHUNK_LENGTH](https://github.com/u-blox/ubxlib/blob/master/common/http_client/src/u_http_client.c#L108) is only employed when a cellular module is in use, it should make no difference for the Wifi case.

**Comment by Tagussan** [comment]
@RobMeades 
Thank you, understood. We made an wrong PR, so closing this.

At first we did not know this library existed and created our own library for communication following the AT Command Manual. Using our library, the PUT upload kept failing with a 400 Bad Request from the server. We also tried a small GET request at first, which was successful.
Then we found this library, read the code, and used it as a guide to change the way the outgoing data is sent: to avoid burdening the UART, the data is divided by `CHUNK_LENGTH` and sent. Our library has exactly the same method as ubxlib at the lowest level. With this change, the PUT upload was successful, we were relieved. However, it was unstable and sometimes failed, so we adjusted `CHUNK_LENGTH`, as mentioned earlier.

We believed that this was also a speed bottleneck in the original library and thought it would be beneficial to report it, so we have created this PR along with our speed result. But we made a wrong PR: the constant that needs to be changed is not  `U_HTTP_CLIENT_CELL_FILE_CHUNK_LENGTH`, but rather `U_HTTP_CLIENT_WIFI_CHUNK_LENGTH`. [And this is just implemented recently in uWifiHttpRequestEx().
](https://github.com/u-blox/ubxlib/blob/43bdf0816d3d282709f7a726119af5290dac4f70/wifi/src/u_wifi_http.c#L489-L503)
However, we believe that `CHUNK_SIZE` is affecting the stability of NINA-W132 anyway. Considering the logic inside NINA-W132, do you still think this is counter-intuitive?

Because it's night here, we will send the result of packet capture tomorrow.

**Comment by RobMeades** [comment]
Ah, now I understand, thanks for the detailed explanation.  You are completely _right_ to have put up a PR, even if it turned out to be not quite the thing in the end, thank you very much for taking the time to do so, we appreciate it and would be interested in any more insights you have.

FYI to @mekm.

**Pull request closed without merging**
