### PR TITLE
ci: add style CI

### PR DESCRIPTION
**Pull request by alonbl**

### CODE REVIEW

**Comment by RobMeades** [comment]
Hmph, looks like we don't pay enough:

image

I'll enquire as to whether those who hold the purse strings want to loosen them somewhat.

**Comment by RobMeades** [comment]
That said, if I accept your commit, I guess the workflow will still be useful for those who fork our repo?

**Comment by RobMeades** [comment]
..and since the error message above says "for private repositories" then, though it won't work on our internal `ubxlib_priv` repo, it will still work here?

**Comment by alonbl** [comment]
@RobMeades I use this in many of my repositories, for public it works for sure. You can disable actions for private that were created for free.

**Comment by alonbl** [comment]
You can see example of run here[1]

[1] https://github.com/alonbl/ubxlib/actions/runs/6518080566

**Comment by RobMeades** [comment]
Very nice indeed!

**Pull request merged**
