### PR TITLE
disable string truncation warning

### PR DESCRIPTION
**Pull request by NathanMOlson**
This "fixes" a compile error experiences on Linux with GCC 11.4.0.

### CODE REVIEW

**Comment by NathanMOlson** [comment]
Error is at `ubxlib/port/platform/linux/src/u_port_uart.c:394:13`

**Comment by RobMeades** [comment]
Interestingly, I changed that very line yesterday, see 208ef1b54cb1fc6e245986b8fbb85ecdf252d4df, so it could be a pointer to a real problem in this case.  Don't suppose you'd be willing to pull `master` from here and see if that happens to have fixed it would you? If it hasn't, I'm also very happy to take your PR as we haven't been able to switch-up to the latest GCC as it messes up something else, and I'm finding this particular GCC warning quite annoying.

**Comment by NathanMOlson** [comment]
@RobMeades I've pulled your latest changes from `master`, and it still fails to compile without [06a0869](https://github.com/u-blox/ubxlib/pull/214/commits/06a0869def8d7994c438491a31fe3ff6e3d37873). With that and [b08e5ab](https://github.com/u-blox/ubxlib/pull/214/commits/b08e5ab0d072c957486e79835934b958c940b120), I've achieved "hello world" with my M9 receiver.

**Comment by RobMeades** [comment]
Thanks for checking, and good catch on the b08e5ab0d072c957486e79835934b958c940b120, we should add a GNSS device connected via USB in our test system to test that case (only have I2C, SPI and UART today). I will pull your PR locally to run through testing, then merge.

**Pull request merged**
